import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";

export default function Reportlists() {
  let navigate = useNavigate();
  const [dataArray, setDataArray] = useState([]);
  let idx = 1;

  useEffect(() => {
    console.log("useEffect Ran");
    async function getData() {
      try {
        const response = await fetch("http://localhost:5000/report/get", {
          method: "POST",
          headers: {
            "Content-type": "application/json",
            Authorization: localStorage.jwttoken,
          },
          body: JSON.stringify({
            email: localStorage.email,
            testreportnum: "",
          }),
        });

        const json = await response.json();
        if (json.message === "Access Denied") {
          navigate("/login");
          alert("Access Denied");
          return;
        }
        const mainData = json.data;
        setDataArray(mainData);
      } catch (error) {
        console.log({ error: error.message });
      }
    }
    getData();
  }, [navigate]);
  return (
    <div>
      {/* NAVBAR */}

      <Navbar />
      {/* Main CONTENT STARTS */}
      <div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name of Agency</th>
              <th scope="col">Test Report Number</th>
              <th scope="col">Sample Name</th>
              <th scope="col">Report Generated On</th>
              <th scope="col">Generated By</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {dataArray.map((data) => {
              return (
                <tr>
                  <th scope="row">{idx++}</th>
                  <td>{data.nameofagency}</td>
                  <td>{data.testreportnum}</td>
                  <td>{data.samplename}ml</td>
                  <td>
                    {new Date(data.issuedate).toLocaleDateString("en-GB")}
                  </td>
                  <td>{localStorage.user}</td>
                  <td>
                    <button
                      type="button"
                      class="btn btn-link"
                      onClick={() => {
                        navigate(`/report/${data.testreportnum}`);
                      }}
                    >
                      Open
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
